"""user patient provider schema update

Revision ID: a0651253187c
Revises: a645d18b8614
Create Date: 2026-03-01 23:07:57.089397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0651253187c'
down_revision: Union[str, Sequence[str], None] = 'a645d18b8614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('providers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('providers', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('providers', 'last_name')
    op.drop_column('providers', 'first_name')
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    # ### end Alembic commands ###
